### PR TITLE
Support for multi parameter 'With' methods

### PR DESCRIPTION
**Pull request by aalmada**
Currently, changing more than one property requires multiple calls to the constructor. This PR adds generation of 'With' methods with more than one parameter and one single call to the constructor. The property/parameter mapping is done by name (like in AutoMapper).

Example: 

```csharp
public class PrimitiveValues
{
    public PrimitiveValues(int value1, string value2, long value3)
    {
        this.Value1 = value1;
        this.Value2 = value2;
        this.Value3 = value3;
    }

    public int Value1 { get; }

    public string Value2 { get; }

    public long Value3 { get; }

    public PrimitiveValues With<T>(T value) => this;
    public PrimitiveValues With(int value1, string value2) => this;
    public PrimitiveValues With(int value1, long value3) => this;
    public PrimitiveValues WithSecondAndThird(string value2, long value3) => this;
}
```

What gets compiled:

```csharp
public class PrimitiveValues
{
    public PrimitiveValues(int value1, string value2, long value3)
    {
        this.Value1 = value1;
        this.Value2 = value2;
        this.Value3 = value3;
    }

    public int Value1 { get; }

    public string Value2 { get; }

    public long Value3 { get; }

    public PrimitiveValues With(int value1)
    {
        return new PrimitiveValues(value1, this.Value2, this.Value3);
    }

    public PrimitiveValues With(string value2)
    {
        return new PrimitiveValues(this.Value1, value2, this.Value3);
    }

    public PrimitiveValues With(long value3)
    {
        return new PrimitiveValues(this.Value1, this.Value2, value3);
    }

    public PrimitiveValues With(int value1, string value2)
    {
        return new PrimitiveValues(value1, value2, this.Value3);
    }

    public PrimitiveValues With(int value1, long value3)
    {
        return new PrimitiveValues(value1, this.Value2, value3);
    }

    public PrimitiveValues WithSecondAndThird(string value2, long value3)
    {
        return new PrimitiveValues(this.Value1, value2, value3);
    }
}
```

Sorry that I'm submitting this without discussion but I started a test just to see if it was possible and just kept going. ;)

I hope I got all the cases right. I tried to not make any breaking change.

I branched from #8 so the differences relative to master may look more complex.

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
I was thinking about that for long time, but still not sure about the way to do that. So in your case you have to manually declare a method for each property combination that you need?

**Comment by aalmada** [comment]
Yes, manually. It's not feasible to automatically come up with naming and all possible combinations.

**Comment by mikhailshilkov** [comment]
What about `With<T1, T2>()` and then all combinations based on type?
Some dynamic thing like `item.With(new { Value1 = 1, Value2 = 2 })` could be nice, but then I don't see a way to make it type-safe.

I've merge your other PR, so please rebase/clean up this one.

**Comment by aalmada** [comment]
@mikhailshilkov Those are interesting proposals but explicit naming should still be supported, just like currently with `With<T>()`.

**Comment by aalmada** [comment]
@mikhailshilkov I've been thinking about your proposal. 
Currently the `With` methods are generated only if there is already a manually inserted one. Usually `With&lt;T&gt;`. Would you required the manual insertion of the multi-type generics? This would be cumbersome for classes with many properties. 
The anonymous class solution is very interesting but would the mapping be done in runtime? That would be a performace penalty. I don't think we can have a signature for anonymous types and create overloads based on it. Would C# 7 tupples fix this?

**Comment by aalmada** [comment]
@mikhailshilkov On an unrelated subject. Can you publish a new version on NuGet or do you think it's too soon? The inheritance support would be usefull for my work project. Thanks.

**Comment by mikhailshilkov** [comment]
If `With` is still generic, it should not depend on amount of properties, right?
Just `With<T1, T2>` would generate `With(a, b)` for each unique combination of types `a` and `b`.
Alternatively, indeed, we can think of generating With(ValueTuple<a, b>) for each combination. Obviously, we'll have a dependency on corresponding Nuget package, but maybe we can make it optional (and fallback to Tuple<a,b>, or no two-param methods). Are you planning to go for C# 7 any time soon?
P.S. Created NuGet 6.1.

**Comment by mikhailshilkov** [comment]
Let's do the following: I'll review & merge your current PR for explicit names, and make a separate issue for implicit names.

**Comment by aalmada** [comment]
Great!
I'll definitely start using C#7 in my personal projects. Unfortunately big companies take a long time to adopt new versions.

**Comment by mikhailshilkov** [comment]
We need to extend the test cases for multiple properties of the same type. In most complex case, we have e.g. `Value1`, `Value2` and `Value3` all of type `int`, and now you want to define `With(value1, value2)` and `With(value1, value3)`. Which is not possible, so we'd have to name them differently.

So, I would say, to be consistent with single-parameter `With`, we should then require the explicit naming `WithValue1Value2(int value1, int value2)`. The short `With` is still ok for unique types, unless it bites us when we implement tuple-based `With`.

**Comment by mikhailshilkov** [comment]
Created #12 for implicit cases

**Comment by mikhailshilkov** [comment]
I'm a bit reluctant to detect which property to assign value to based on method parameter name. For a method
`WithBla(int value1, int value2)` the usage will be like `WithBla(111, 222)`. When reading the usage there's no way to see which parameter is `111` and which is `222`.
That was the original motivation behind explicit names like `WithValue1()`, and now we are changing this for multi-parameter methods.
The alternative `WithValue1Value2()` looks ugly but is at least explicit.
What's your opinion? Or should we support both and leave this to the user?

**Comment by aalmada** [comment]
My reasoning was that most of the times developers will use `WithValue1Value2()` but I wanted to give them freedom to make their own names in cases it makes sense. 
The use of parameter names also makes it easier to parse. We could split the names of the `With` methods by uppercase letters but properties may have long names with multiple uppercase letters.

**Comment by mikhailshilkov** [comment]
I've finally merged your PR. Tested in my solution - no regression found. Also fixed one test and extended the README.

**Pull request merged**
