### PR TITLE
Support for inheritance with assembly references

### PR DESCRIPTION
**Pull request by aalmada**
This is my attempt to add support for inheritance with classes in different assemblies but in the same folder. This would be the most common scenario.
Added assembly resolvers in weaver and in the tests but the module is still not saving successfully.
@mikhailshilkov Do you experience with assembly/type resolution in Cecil?

### CODE REVIEW

**Comment by aalmada** [comment]
No problem. I like the new names.

**Comment by aalmada** [comment]
@mikhailshilkov I fixed the build but please don't merge yet. It's still not working.

**Comment by aalmada** [comment]
@mikhailshilkov Passing all tests. I'd like to test it a real project build. How do you do it?

**Comment by mikhailshilkov** [comment]
You can build a package with a new version, make a local NuGet feed (from local folder) and put the package there.
Or just hack-copy the dll to your packages folder and rebuild.

**Comment by aalmada** [comment]
Looks like the referenced type is not resolved correctly. :(

2>MSBUILD : error : Fody: An unhandled exception occurred:
2>MSBUILD : error : Exception:
2>MSBUILD : error : Value cannot be null.
2>MSBUILD : error : Parameter name: type
2>MSBUILD : error : StackTrace:
2>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type, IGenericParameterProvider context)
2>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type)
2>MSBUILD : error :    at ModuleWeaver.GetAllProperties(TypeReference type)
2>MSBUILD : error :    at ModuleWeaver.GetAllProperties(TypeDefinition type)
2>MSBUILD : error :    at ModuleWeaver.GetAllProperties(TypeReference type)
2>MSBUILD : error :    at ModuleWeaver.GetAllProperties(TypeDefinition type)
2>MSBUILD : error :    at ModuleWeaver.<>c__DisplayClass19_0.<GetValidConstructor>b__1(ParameterDefinition par)
2>MSBUILD : error :    at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
2>MSBUILD : error :    at ModuleWeaver.<>c__DisplayClass19_0.<GetValidConstructor>b__0(MethodDefinition ctor)
2>MSBUILD : error :    at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
2>MSBUILD : error :    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
2>MSBUILD : error :    at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
2>MSBUILD : error :    at ModuleWeaver.GetValidConstructor(TypeDefinition type)
2>MSBUILD : error :    at ModuleWeaver.Execute()
2>MSBUILD : error :    at lambda_method(Closure , Object )
2>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
2>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
2>MSBUILD : error : Source:
2>MSBUILD : error : Mono.Cecil
2>MSBUILD : error : TargetSite:
2>MSBUILD : error : Mono.Cecil.TypeReference ImportReference(Mono.Cecil.TypeReference, Mono.Cecil.IGenericParameterProvider)
2>MSBUILD : error :

**Comment by aalmada** [comment]
The exception happens if the referenced assembly is a PCL :o

**Comment by aalmada** [comment]
@mikhailshilkov Everything's working! Looks like PCL's have to be Profile433.

**Comment by aalmada** [comment]
@mikhailshilkov Tested now on my work project and it does work on a multi-assembly build.

**Comment by mikhailshilkov** [comment]
I don't have this case in my projects... Time to integrate?

**Comment by aalmada** [comment]
Unless you have comments about the code

**Pull request merged**
